import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on("pageerror", (e) => console.log("ERR", String(e)));
await page.goto("http://127.0.0.1:8080/", { waitUntil: "domcontentloaded" });
await page.getByRole("button", { name: /enter the palace/i }).first().click();
await page.getByRole("button", { name: /^deploy$/i }).click();
await page.waitForFunction(() => Boolean(window.__controlsTest), { timeout: 50000 });
const pos = await page.evaluate(() => window.__controlsTest.getPos());
await page.keyboard.press("KeyI");
await page.waitForTimeout(300);
const bag = await page.getByRole("button", { name: /close/i }).count();
await page.keyboard.press("KeyI");
await page.waitForTimeout(100);
await page.keyboard.press("KeyM");
await page.waitForTimeout(400);
const atlas = await page.locator('img[alt="Crimson Sovereign open world"]').count();
const pulse = await page.locator('img[src="/ui/pulse-frame.png"]').count();
console.log(JSON.stringify({ pos, bag, atlas, pulse }));
if (Math.abs(pos.z - 68) > 3 || bag < 1 || atlas < 1 || pulse < 1) process.exit(1);
console.log("PASS");
await browser.close();
